---
title: "4110 Prelim II"
author: "Michael Cao, Taren Daniels, Aristotle Kolefas"
date: "2022-11-18"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(nlme)
library(pROC)
library(lmtest)
```

```{r}
policing2 <- read.csv("policing2.csv")
```
#########################################
#1: EXECUTIVE SUMMARY
#2: INTRODUCTION
#3: DESCRIPTION OF SUBJECTS
#4: RESULTS
#5: DISCUSSION
#########################################
```{r}
# PART 1: DATA PRE-PROCESSING

# 1) Remove na rows
nrow(policing2)
policing2 <- na.omit(policing2)
nrow(policing2)

# 2) Clean data
dim(policing2)
policing2 <- policing2[policing2$held == 1 | 
                       policing2$held == 0,]
table(policing2$held)
dim(policing2)
policing2 <- policing2[policing2$race == "Black" | 
                       policing2$race == "White",]
dim(policing2)
policing2 <- policing2[policing2$sex == "Male" | 
                       policing2$sex == "Female",] 
dim(policing2)
policing2 <- policing2[policing2$prior.traffic == 0 | 
                       policing2$prior.traffic == 1 |
                       policing2$prior.traffic == 2,]
dim(policing2)
policing2 <- policing2[policing2$region == "North" | 
                       policing2$region == "South" | 
                       policing2$region == "West" | 
                       policing2$region == "East",]
dim(policing2)
policing2 <- policing2[policing2$employed == "No" | 
                       policing2$employed == "Yes",]
dim(policing2)
policing2 <- policing2[policing2$citizen == "No" | 
                       policing2$citizen == "Yes",]
dim(policing2)
policing2 <- policing2[0 <= policing2$databases & 
                       policing2$databases <= 6,]
dim(policing2)
policing2 <- policing2[2000 <= policing2$year & 
                       policing2$year <= 2006,]
dim(policing2)
policing2 <- policing2[!apply(
  policing2[,c("id_num", "held", "race", "sex",
               "prior.traffic", "region", "employed",
               "citizen", "databases", "year", "age")], 
  1, anyNA),]
dim(policing2)

# 3) Check if id_num is unique
nrow(policing2) == length(unique(policing2$id_num))

# 4) Convert all rows with database = 6 to database = 5
for(j in 1:length(policing2$databases)) 
{
  if(policing2$databases[j] > 5) 
  {
    policing2$databases[j] <- 5 
  }
  else 
  {
    policing2$databases[j] <- policing2$databases[j]
  }
}

# 5) Re-encode year
for(j in 1:length(policing2$year)) 
{
  if(2001 <= policing2$year[j] & policing2$year[j] <= 2003) 
  {
    policing2$year[j] <- "Before 2004"
  }
  else 
  {
    policing2$year[j] <- "2004 or later"
  }
}

# 6) Remove extreme values for age
policing2 <- policing2[policing2$age > 10 & policing2$age < 100,]
dim(policing2)
```

```{r}
# PART 2: DESCRIPTIVE STATISTICS

# id_num is meaningless for the dataset, so we remove this column
policing2<-policing2[ , !names(policing2) %in% c("id_num" )]

# Summary table for seven categorical variables 
# (race, sex, prior.traffic, region, employed, citizen, year)
race.table<-rbind(cbind("Held"=table(policing2$race[policing2$held==1]), 
                       "Pr(Held)"=table(policing2$race[policing2$held==1])/
                        table(policing2$race), 
                       "Not Held"=table(policing2$race[policing2$held==0]),
                       "Pr(Not Held)"=table(policing2$race[policing2$held==0])/
                        table(policing2$race), 
                       "Total"=table(policing2$race)),
                  "Total"=c(nrow(policing2[policing2$held==1,]),1,
                            nrow(policing2[policing2$held==0,]),1,nrow(policing2)))
race.table
sex.table<-rbind(cbind("Held"=table(policing2$sex[policing2$held==1]), 
                       "Pr(Held)"=table(policing2$sex[policing2$held==1])/
                       table(policing2$sex), 
                       "Not Held"=table(policing2$sex[policing2$held==0]),
                       "Pr(Not Held)"=table(policing2$sex[policing2$held==0])/
                       table(policing2$sex), 
                       "Total"=table(policing2$sex)), 
                 "Total"=c(nrow(policing2[policing2$held==1,]),1,
                           nrow(policing2[policing2$held==0,]),1,nrow(policing2)))
sex.table
traffic.table<-rbind(cbind("Held"=table(policing2$prior.traffic[policing2$held==1]), 
                       "Pr(Held)"=table(policing2$prior.traffic[policing2$held==1])/
                           table(policing2$prior.traffic), 
                       "Not Held"=table(policing2$prior.traffic[policing2$held==0]),
                       "Pr(Not Held)"=table(policing2$prior.traffic[policing2$held==0])/
                           table(policing2$prior.traffic), 
                       "Total"=table(policing2$prior.traffic)), 
                 "Total"=c(nrow(policing2[policing2$held==1,]),1,
                           nrow(policing2[policing2$held==0,]),1,nrow(policing2)))
traffic.table
region.table<-rbind(cbind("Held"=table(policing2$region[policing2$held==1]), 
                       "Pr(Held)"=table(policing2$region[policing2$held==1])/
                          table(policing2$region), 
                       "Not Held"=table(policing2$region[policing2$held==0]),
                       "Pr(Not Held)"=table(policing2$region[policing2$held==0])/
                          table(policing2$region), 
                       "Total"=table(policing2$region)), 
                 "Total"=c(nrow(policing2[policing2$held==1,]),1,
                           nrow(policing2[policing2$held==0,]),1,nrow(policing2)))
region.table
employed.table<-rbind(cbind("Held"=table(policing2$employed[policing2$held==1]), 
                       "Pr(Held)"=table(policing2$employed[policing2$held==1])/
                            table(policing2$employed), 
                       "Not Held"=table(policing2$employed[policing2$held==0]),
                       "Pr(Not Held)"=table(policing2$employed[policing2$held==0])/
                            table(policing2$employed), 
                       "Total"=table(policing2$employed)), 
                 "Total"=c(nrow(policing2[policing2$held==1,]),1,
                           nrow(policing2[policing2$held==0,]),1,nrow(policing2)))
employed.table
citizen.table<-rbind(cbind("Held"=table(policing2$citizen[policing2$held==1]), 
                       "Pr(Held)"=table(policing2$citizen[policing2$held==1])/
                           table(policing2$citizen), 
                       "Not Held"=table(policing2$citizen[policing2$held==0]),
                       "Pr(Not Held)"=table(policing2$citizen[policing2$held==0])/
                           table(policing2$citizen), 
                       "Total"=table(policing2$citizen)), 
                 "Total"=c(nrow(policing2[policing2$held==1,]),1,
                           nrow(policing2[policing2$held==0,]),1,nrow(policing2)))
citizen.table
year.table<-rbind(cbind("Held"=table(policing2$year[policing2$held==1]), 
                       "Pr(Held)"=table(policing2$year[policing2$held==1])/
                        table(policing2$year), 
                       "Not Held"=table(policing2$year[policing2$held==0]),
                       "Pr(Not Held)"=table(policing2$year[policing2$held==0])/
                        table(policing2$year), 
                       "Total"=table(policing2$year)), 
                 "Total"=c(nrow(policing2[policing2$held==1,]),1,
                           nrow(policing2[policing2$held==0,]),1,nrow(policing2)))
year.table

# Summary statistics for two numerical variables (databases, age)
summary(policing2$databases)
summary(policing2$age)
```



```{r}
# PART 3: TWO-WAY TABLES (outcome variable with each predictor, one at a time)

# 1) Chi-squared tests for each variable vs response
race_tab <- table(policing2$race, policing2$held)
chisq.test(race_tab)
sex_tab <- table(policing2$sex, policing2$held)
chisq.test(sex_tab)
traff_tab <- table(policing2$prior.traffic, policing2$held)
chisq.test(traff_tab)
region_tab <- table(policing2$region, policing2$held)
chisq.test(region_tab)
employed_tab <- table(policing2$employed, policing2$held)
chisq.test(employed_tab)
citizen_tab <- table(policing2$citizen, policing2$held)
chisq.test(citizen_tab)
year_tab <- table(policing2$year, policing2$held)
chisq.test(year_tab)
chisq.test(policing2$databases)
chisq.test(policing2$age)

# 2) Likelihood Ratio Test for Numerical Variables

## Age Numerical Variable
glm.age.int <- glm(held~1, data = policing2, family = binomial)
glm.age <- glm(held~age, data = policing2, family = binomial)
lrtest(glm.age.int, glm.age)

## Databases Numerical Variable
glm.database.int <- glm(held~1, data = policing2, family = binomial)
glm.databases <- glm(held~databases, data = policing2, family = binomial)
lrtest(glm.database.int, glm.databases)

# 3) Remove three variables based on chi-squared results
policing2<-policing2[ , !names(policing2) %in% c("region" )]
policing2<-policing2[ , !names(policing2) %in% c("prior.traffic" )]
policing2<-policing2[ , !names(policing2) %in% c("sex" )]

# 4) Mosaic plot for each variable vs response
par(mfrow=c(2,2))
spineplot(race_tab, col=c("#07798D", "#7BCB9F"), 
          xlab = "Race", ylab = "Held", yaxlabels=c("Not held", "Held"))
spineplot(employed_tab, col=c("#07798D", "#7BCB9F"), 
          xlab = "Employed", ylab = "Held",yaxlabels=c("Not held", "Held"))
spineplot(citizen_tab, col=c("#07798D", "#7BCB9F"), 
          xlab = "Citizen", ylab = "Held",yaxlabels=c("Not held", "Held"))
spineplot(year_tab, col=c("#07798D", "#7BCB9F"), 
          xlab = "Year", ylab = "Held",yaxlabels=c("Not held", "Held"))

# 5) Slicing plots for two numerical variables (databases and age)
dat.fac  <- factor(cut(policing2$databases, breaks=5))
dat.prob<- tapply(policing2$held, dat.fac, mean)
dat.slice.avg <- tapply(policing2$databases, dat.fac, mean)
dat.logits <- log(dat.prob/(1-dat.prob))
plot(dat.slice.avg,dat.logits, ylab = "Empirical Log-Odds", 
     ylim = c(-2.5,0), xlim = c(0,6),  xlab = "Slice",
     main = "Slicing Plot for Databases : Empirical Log-Odds")

age.fac <- factor(cut(policing2$age, breaks=c(10,15,20,25,30,35,40,45,50)))
age.prob <- tapply(policing2$held, age.fac, mean)
age.slice.avg <- tapply(policing2$age, age.fac, mean)
age.logits <- log(age.prob/(1-age.prob))
plot(age.slice.avg,age.logits, ylab = "Empirical Log-Odds", 
     ylim = c(-2,0), xlim = c(10,60), xlab = "Slice",
     main = "Slicing Plot for Age : Empirical Log-Odds")
```



```{r}
# PART 4: CONSIDER MODEL OPTIONS (which variables, transformation of variables, consider interaction effects)

# 1) Correlations between predictors
policing2_ind <- policing2
for(k in 1:length(policing2_ind$race)) 
{
  if(policing2_ind$race[k] == "White") 
  {
    policing2_ind$race[k] <- 1 
  }
  else 
  {
    policing2_ind$race[k] <- 0
  }
}

for(k in 1:length(policing2_ind$employed)) 
{
  if(policing2_ind$employed[k] == "Yes") 
  {
    policing2_ind$employed[k] <- 1 
  }
  else 
  {
    policing2_ind$employed[k] <- 0
  }
}

for(k in 1:length(policing2_ind$citizen)) 
{
  if(policing2_ind$citizen[k] == "Yes") 
  {
    policing2_ind$citizen[k] <- 1 }
  else 
  {
    policing2_ind$citizen[k] <- 0
  }
}

for(p in 1:length(policing2_ind$year)) 
{
  if(policing2_ind$year[p] == "Before 2004") 
  {
    policing2_ind$year[p] <- 1 
  }
  else 
  {
    policing2_ind$year[p] <- 0
  }
}

policing2_ind$race <- as.numeric(policing2_ind$race)
policing2_ind$employed <- as.numeric(policing2_ind$employed)
policing2_ind$citizen <- as.numeric(policing2_ind$citizen)
policing2_ind$databases <- as.numeric(policing2_ind$databases)
policing2_ind$year <- as.numeric(policing2_ind$year)
policing2_ind$age <- as.numeric(policing2_ind$age)

policing2_ind_subset <- data.frame(race = policing2_ind$race, employed = policing2_ind$employed, citizen = policing2_ind$citizen, databases = policing2_ind$databases, year = policing2_ind$year, age = policing2_ind$age)

cor(policing2_ind_subset)
# None of the correlations is above 0.25, so none of these six predictors should be removed.

# 2) Consider interaction plots
# interactions between 2 categorical variables
interactions<- combn(c(2,3,4,6),2)
par(mfrow=c(2,3))
for (i in 1:6)
{
  interaction.plot(x.factor = policing2[,interactions[2,i]], 
                 trace.factor = policing2[,interactions[1,i]],
                 response = policing2[,1],
                 ylab = "Held",
                 xlab = colnames(policing2)[interactions[2,i]],
                 col = c("pink", "blue"),
                 lty = 1, #line type
                 lwd = 2, #line width
                 trace.label = colnames(policing2)[interactions[1,i]])
}

# interactions between 1 categorical and 1 numerical variable
interactions<- combn(c(2,3,4,6),1)
par(mfrow=c(2,4))
for (j in c(5,7))
{
  for (i in 1:4)
  {
    interaction.plot(x.factor = policing2[,j], 
                     trace.factor = policing2[,interactions[1,i]],
                     response = policing2[,1],
                     ylab = "Held",
                     xlab = colnames(policing2)[j],
                     col = c("pink", "blue"),
                     lty = 1, #line type
                     lwd = 2, #line width
                     trace.label = colnames(policing2)[interactions[1,i]])
  }
}

# From the interaction plots above, we conclude that interactions citizen:employed, race:employed, race:citizen, and database:employed are not significant. 
```

```{r}
# PART 5: FIT, COMPARE, SELECT MODELS

# Best subset selection including all possible combinations of the six variables
# Requires: response is the first column of dat
bestModelFinder <- function(dat)
{
  models<-c()
  AIC<-c(); BIC<-c()
  for (i in 1:ncol(dat)-1)
  {
    cat("i=",i,"\n")
    comb <- combn(2:ncol(dat), i)
    for (j in 1:ncol(comb))
    {
      cat("j=",j,"\n")
      dat.temp <- data.frame(dat[, c(1,comb[,j])])
      if (ncol(dat.temp)>=3)
      {
        comb.interaction <- combn(2:ncol(dat.temp), 2) 
        for (k in 1:ncol(comb.interaction))
        {
          cat("k=",k,"\n")
          comb.interaction.comb <- combn(1:ncol(comb.interaction), k)
          for (l in 1:ncol(comb.interaction.comb))
          {
            interactions<-""
            for (m in 1:k)
            {
              interactions<-paste0(interactions,"+",colnames(dat.temp)
                                   [comb.interaction[1,comb.interaction.comb[m,l]]],
                                   ":", colnames(dat.temp)
                                   [comb.interaction[2,comb.interaction.comb[m,l]]])
            }
            glm.temp <- glm(as.formula(paste0(colnames(dat.temp)[1], "~.", interactions)),
                            data=dat.temp, family=binomial)
            models<-append(models, Reduce(paste0, deparse(formula(glm.temp))))
            BIC<-append(BIC, BIC(glm.temp))
            AIC<-append(AIC, AIC(glm.temp))
          }
        }
      }
      else
      {
        glm.temp <- glm(as.formula(paste0(colnames(dat.temp)[1], "~.")), 
                        data=dat.temp, family=binomial)
        models<-append(models, Reduce(paste0, deparse(formula(glm.temp))))
        BIC<-append(BIC, BIC(glm.temp))
        AIC<-append(AIC, AIC(glm.temp))
      }
    }
  }
  summary <- data.frame(models, AIC, BIC)
  
  cat("Top 5 AIC Models:", "\n")
  print(head(summary[order(summary$AIC),],5))
  cat("\n","Top 5 BIC Models:", "\n")
  print(head(summary[order(summary$BIC),],5))
  
  cat("\n", "Model", summary$models[which.min(summary$AIC)],
      "returns the lowest AIC of", min(summary$AIC), "\n")
  cat("\n", "Model", summary$models[which.min(summary$BIC)],
      "returns the lowest BIC of", min(summary$BIC), "\n")
}

#bestModelFinder(policing2)

# The best AIC model has significantly more terms than the best BIC model, but we will assess the fit on both models to make our decision.
```

```{r}
### Probability Plots:
## Probability Plots for model with lowest AIC (on databases):
optimal.AIC <- glm(held ~ race + employed + citizen + databases + year + age + race:year + race:age + employed:year + employed:age + citizen:databases + citizen:year + databases:year + year:age, family = binomial, data = policing2)

databases.vals <- seq(0, 5, 0.05)

# Most people are employed, citizens, charged after 2004, and of age 19. 

## Databases as predictor, race as categorical variable
num_databases_white <- exp(optimal.AIC$coefficients[1] + optimal.AIC$coefficients[2]*1 + optimal.AIC$coefficients[3]*1 + optimal.AIC$coefficients[4]*1 + optimal.AIC$coefficients[5]*databases.vals + optimal.AIC$coefficients[6]*0 + optimal.AIC$coefficients[7]*19 + optimal.AIC$coefficients[8]*1*0 + optimal.AIC$coefficients[9]*1*19 + optimal.AIC$coefficients[10]*1*0 + optimal.AIC$coefficients[11]*1*19 + optimal.AIC$coefficients[12]*1*databases.vals + optimal.AIC$coefficients[13]*1*0 + optimal.AIC$coefficients[14]*databases.vals*0 + optimal.AIC$coefficients[15]*1*19)
denom_databases_white <- 1 + num_databases_white
probs_databases_white <- num_databases_white/denom_databases_white
  
plot(databases.vals, probs_databases_white, type = "l", ylim = c(0, 0.4), xlab = "Databases", ylab = "Predicted Probability of being Held", main = "Pred. Prob. of being Held by race and number of databases", col = "blue")
legend(0, 0.25, legend = c("White", "Black"), col = c("blue", "red"), lty = 1:1, cex = 0.8, box.lty = 2, box.lwd = 2, box.col = "green")

num_databases_black <- exp(optimal.AIC$coefficients[1] + optimal.AIC$coefficients[2]*0 + optimal.AIC$coefficients[3]*1 + optimal.AIC$coefficients[4]*1 + optimal.AIC$coefficients[5]*databases.vals + optimal.AIC$coefficients[6]*0 + optimal.AIC$coefficients[7]*19 + optimal.AIC$coefficients[8]*0*0 + optimal.AIC$coefficients[9]*0*19 + optimal.AIC$coefficients[10]*1*0 + optimal.AIC$coefficients[11]*0*19 + optimal.AIC$coefficients[12]*1*databases.vals + optimal.AIC$coefficients[13]*1*0 + optimal.AIC$coefficients[14]*databases.vals*0 + optimal.AIC$coefficients[15]*0*19)
denom_databases_black <- 1 + num_databases_black
probs_databases_black <- num_databases_black/denom_databases_black

lines(databases.vals, probs_databases_black, col = "red")

## Databases as predictor, employment status as categorical variable
num_databases_emp <- exp(optimal.AIC$coefficients[1] + optimal.AIC$coefficients[2]*1 + optimal.AIC$coefficients[3]*1 + optimal.AIC$coefficients[4]*1 + optimal.AIC$coefficients[5]*databases.vals + optimal.AIC$coefficients[6]*0 + optimal.AIC$coefficients[7]*19 + optimal.AIC$coefficients[8]*1*0 + optimal.AIC$coefficients[9]*1*19 + optimal.AIC$coefficients[10]*1*0 + optimal.AIC$coefficients[11]*1*19 + optimal.AIC$coefficients[12]*1*databases.vals + optimal.AIC$coefficients[13]*1*0 + optimal.AIC$coefficients[14]*databases.vals*0 + optimal.AIC$coefficients[15]*0*19)
denom_databases_emp <- 1 + num_databases_emp
probs_databases_emp <- num_databases_emp/denom_databases_emp
  
plot(databases.vals, probs_databases_emp, type = "l", ylim = c(0, 0.6), xlab = "Databases", ylab = "Predicted Probability of being Held", main = "Pred. Prob. of being Held by emp. stat. and number of databases", col = "blue")
legend(0, 0.30, legend = c("Employed", "Unemployed"), col = c("blue", "red"), lty = 1:1, cex = 0.8, box.lty = 2, box.lwd = 2, box.col = "green")

num_databases_unemp <- exp(optimal.AIC$coefficients[1] + optimal.AIC$coefficients[2]*1 + optimal.AIC$coefficients[3]*0 + optimal.AIC$coefficients[4]*1 + optimal.AIC$coefficients[5]*databases.vals + optimal.AIC$coefficients[6]*0 + optimal.AIC$coefficients[7]*19 + optimal.AIC$coefficients[8]*1*0 + optimal.AIC$coefficients[9]*1*19 + optimal.AIC$coefficients[10]*0*0 + optimal.AIC$coefficients[11]*0*19 + optimal.AIC$coefficients[12]*1*databases.vals + optimal.AIC$coefficients[13]*1*0 + optimal.AIC$coefficients[14]*databases.vals*0 + optimal.AIC$coefficients[15]*0*19)
denom_databases_unemp <- 1 + num_databases_unemp
probs_databases_unemp <- num_databases_unemp/denom_databases_unemp

lines(databases.vals, probs_databases_unemp, col = "red")

## Databases as predictor, citizenship as categorical variable
num_databases_cit <- exp(optimal.AIC$coefficients[1] + optimal.AIC$coefficients[2]*1 + optimal.AIC$coefficients[3]*1 + optimal.AIC$coefficients[4]*1 + optimal.AIC$coefficients[5]*databases.vals + optimal.AIC$coefficients[6]*0 + optimal.AIC$coefficients[7]*19 + optimal.AIC$coefficients[8]*1*0 + optimal.AIC$coefficients[9]*1*19 + optimal.AIC$coefficients[10]*1*0 + optimal.AIC$coefficients[11]*1*19 + optimal.AIC$coefficients[12]*1*databases.vals + optimal.AIC$coefficients[13]*1*0 + optimal.AIC$coefficients[14]*databases.vals*0 + optimal.AIC$coefficients[15]*0*19)
denom_databases_cit <- 1 + num_databases_cit
probs_databases_cit <- num_databases_cit/denom_databases_cit
  
plot(databases.vals, probs_databases_emp, type = "l", ylim = c(0, 0.5), xlab = "Databases", ylab = "Predicted Probability of being Held", main = "Pred. Prob. of being Held by cit. stat. and number of databases", col = "blue")
legend(0, 0.35, legend = c("Citizen", "Not citizen"), col = c("blue", "red"), lty = 1:1, cex = 0.8, box.lty = 2, box.lwd = 2, box.col = "green")

num_databases_nocit <- exp(optimal.AIC$coefficients[1] + optimal.AIC$coefficients[2]*1 + optimal.AIC$coefficients[3]*1 + optimal.AIC$coefficients[4]*0 + optimal.AIC$coefficients[5]*databases.vals + optimal.AIC$coefficients[6]*0 + optimal.AIC$coefficients[7]*19 + optimal.AIC$coefficients[8]*1*0 + optimal.AIC$coefficients[9]*1*19 + optimal.AIC$coefficients[10]*1*0 + optimal.AIC$coefficients[11]*1*19 + optimal.AIC$coefficients[12]*0*databases.vals + optimal.AIC$coefficients[13]*0*0 + optimal.AIC$coefficients[14]*databases.vals*0 + optimal.AIC$coefficients[15]*0*19)
denom_databases_nocit <- 1 + num_databases_nocit
probs_databases_nocit <- num_databases_nocit/denom_databases_nocit

lines(databases.vals, probs_databases_nocit, col = "red")

## Databases as predictor, year as categorical variable
num_databases_bf2004 <- exp(optimal.AIC$coefficients[1] + optimal.AIC$coefficients[2]*1 + optimal.AIC$coefficients[3]*1 + optimal.AIC$coefficients[4]*1 + optimal.AIC$coefficients[5]*databases.vals + optimal.AIC$coefficients[6]*1 + optimal.AIC$coefficients[7]*19 + optimal.AIC$coefficients[8]*1*1 + optimal.AIC$coefficients[9]*1*19 + optimal.AIC$coefficients[10]*1*1 + optimal.AIC$coefficients[11]*1*19 + optimal.AIC$coefficients[12]*1*databases.vals + optimal.AIC$coefficients[13]*1*1 + optimal.AIC$coefficients[14]*databases.vals*1 + optimal.AIC$coefficients[15]*1*19)
denom_databases_bf2004 <- 1 + num_databases_bf2004
probs_databases_bf2004 <- num_databases_bf2004/denom_databases_bf2004
  
plot(databases.vals, probs_databases_bf2004, type = "l", ylim = c(0, 0.4), xlab = "Databases", ylab = "Predicted Probability of being Held", main = "Pred. Prob. of being Held by time period and number of databases", col = "blue")
legend(0, 0.25, legend = c("Before 2004", "2004 or later"), col = c("blue", "red"), lty = 1:1, cex = 0.8, box.lty = 2, box.lwd = 2, box.col = "green")

num_databases_2004l <- exp(optimal.AIC$coefficients[1] + optimal.AIC$coefficients[2]*1 + optimal.AIC$coefficients[3]*1 + optimal.AIC$coefficients[4]*1 + optimal.AIC$coefficients[5]*databases.vals + optimal.AIC$coefficients[6]*0 + optimal.AIC$coefficients[7]*19 + optimal.AIC$coefficients[8]*1*0 + optimal.AIC$coefficients[9]*1*19 + optimal.AIC$coefficients[10]*1*0 + optimal.AIC$coefficients[11]*1*19 + optimal.AIC$coefficients[12]*1*databases.vals + optimal.AIC$coefficients[13]*1*0 + optimal.AIC$coefficients[14]*databases.vals*0 + optimal.AIC$coefficients[15]*0*19)
denom_databases_2004l <- 1 + num_databases_2004l
probs_databases_2004l <- num_databases_2004l/denom_databases_2004l

lines(databases.vals, probs_databases_2004l, col = "red")

# Probability Plots for model with lowest AIC (on age):
age.vals <- seq(1, 70, 0.5)

# Most people are employed, citizens, charged after 2004, and are in 0 databases. 

## Age as predictor, race as categorical variable
num_age_white <- exp(optimal.AIC$coefficients[1] + optimal.AIC$coefficients[2]*1 + optimal.AIC$coefficients[3]*1 + optimal.AIC$coefficients[4]*1 + optimal.AIC$coefficients[5]*0 + optimal.AIC$coefficients[6]*0 + optimal.AIC$coefficients[7]*age.vals + optimal.AIC$coefficients[8]*1*0 + optimal.AIC$coefficients[9]*1*age.vals + optimal.AIC$coefficients[10]*1*0 + optimal.AIC$coefficients[11]*1*age.vals + optimal.AIC$coefficients[12]*1*0 + optimal.AIC$coefficients[13]*1*0 + optimal.AIC$coefficients[14]*0*0 + optimal.AIC$coefficients[15]*1*age.vals)
denom_age_white <- 1 + num_age_white
probs_age_white <- num_age_white/denom_age_white
  
plot(age.vals, probs_age_white, type = "l", ylim = c(0, 0.20), xlab = "Age", ylab = "Predicted Probability of being Held", main = "Pred. Prob. of being Held by race and age", col = "blue")
legend(0, 0.15, legend = c("White", "Black"), col = c("blue", "red"), lty = 1:1, cex = 0.8, box.lty = 2, box.lwd = 2, box.col = "green")

num_age_black <- exp(optimal.AIC$coefficients[1] + optimal.AIC$coefficients[2]*0 + optimal.AIC$coefficients[3]*1 + optimal.AIC$coefficients[4]*1 + optimal.AIC$coefficients[5]*0 + optimal.AIC$coefficients[6]*0 + optimal.AIC$coefficients[7]*age.vals + optimal.AIC$coefficients[8]*0*0 + optimal.AIC$coefficients[9]*0*age.vals + optimal.AIC$coefficients[10]*1*0 + optimal.AIC$coefficients[11]*0*age.vals + optimal.AIC$coefficients[12]*1*0 + optimal.AIC$coefficients[13]*1*0 + optimal.AIC$coefficients[14]*0*0 + optimal.AIC$coefficients[15]*0*age.vals)
denom_age_black <- 1 + num_age_black
probs_age_black <- num_age_black/denom_age_black

lines(age.vals, probs_age_black, col = "red")

## Age as predictor, employment status as categorical variable
num_age_emp <- exp(optimal.AIC$coefficients[1] + optimal.AIC$coefficients[2]*1 + optimal.AIC$coefficients[3]*1 + optimal.AIC$coefficients[4]*1 + optimal.AIC$coefficients[5]*0 + optimal.AIC$coefficients[6]*0 + optimal.AIC$coefficients[7]*age.vals + optimal.AIC$coefficients[8]*1*0 + optimal.AIC$coefficients[9]*1*age.vals + optimal.AIC$coefficients[10]*1*0 + optimal.AIC$coefficients[11]*1*age.vals + optimal.AIC$coefficients[12]*1*0 + optimal.AIC$coefficients[13]*1*0 + optimal.AIC$coefficients[14]*0*0 + optimal.AIC$coefficients[15]*0*age.vals)
denom_age_emp <- 1 + num_age_emp
probs_age_emp <- num_age_emp/denom_age_emp
  
plot(age.vals, probs_age_emp, type = "l", xlab = "Age", ylab = "Predicted Probability of being Held", main = "Pred. Prob. of being Held by emp. stat. and age", col = "blue")
legend(0, 0.11, legend = c("Employed", "Unemployed"), col = c("blue", "red"), lty = 1:1, cex = 0.8, box.lty = 2, box.lwd = 2, box.col = "green")

num_age_unemp <- exp(optimal.AIC$coefficients[1] + optimal.AIC$coefficients[2]*1 + optimal.AIC$coefficients[3]*0 + optimal.AIC$coefficients[4]*1 + optimal.AIC$coefficients[5]*0 + optimal.AIC$coefficients[6]*0 + optimal.AIC$coefficients[7]*age.vals + optimal.AIC$coefficients[8]*1*0 + optimal.AIC$coefficients[9]*1*age.vals + optimal.AIC$coefficients[10]*0*0 + optimal.AIC$coefficients[11]*0*age.vals + optimal.AIC$coefficients[12]*1*0 + optimal.AIC$coefficients[13]*1*0 + optimal.AIC$coefficients[14]*0*0 + optimal.AIC$coefficients[15]*0*age.vals)
denom_age_unemp <- 1 + num_age_unemp
probs_age_unemp <- num_age_unemp/denom_age_unemp

lines(age.vals, probs_age_unemp, col = "red")

## Age as predictor, citizenship as categorical variable
num_age_cit <- exp(optimal.AIC$coefficients[1] + optimal.AIC$coefficients[2]*1 + optimal.AIC$coefficients[3]*1 + optimal.AIC$coefficients[4]*1 + optimal.AIC$coefficients[5]*0 + optimal.AIC$coefficients[6]*0 + optimal.AIC$coefficients[7]*age.vals + optimal.AIC$coefficients[8]*1*0 + optimal.AIC$coefficients[9]*1*age.vals + optimal.AIC$coefficients[10]*1*0 + optimal.AIC$coefficients[11]*1*age.vals + optimal.AIC$coefficients[12]*1*0 + optimal.AIC$coefficients[13]*1*0 + optimal.AIC$coefficients[14]*0*0 + optimal.AIC$coefficients[15]*0*age.vals)
denom_age_cit <- 1 + num_age_cit
probs_age_cit <- num_age_cit/denom_age_cit
  
plot(age.vals, probs_age_emp, type = "l", ylim = c(0,0.40), xlab = "Age", ylab = "Predicted Probability of being Held", main = "Pred. Prob. of being Held by cit. stat. and age", col = "blue")
legend(0, 0.25, legend = c("Citizen", "Not citizen"), col = c("blue", "red"), lty = 1:1, cex = 0.8, box.lty = 2, box.lwd = 2, box.col = "green")

num_age_nocit <- exp(optimal.AIC$coefficients[1] + optimal.AIC$coefficients[2]*1 + optimal.AIC$coefficients[3]*1 + optimal.AIC$coefficients[4]*0 + optimal.AIC$coefficients[5]*0 + optimal.AIC$coefficients[6]*0 + optimal.AIC$coefficients[7]*age.vals + optimal.AIC$coefficients[8]*1*0 + optimal.AIC$coefficients[9]*1*age.vals + optimal.AIC$coefficients[10]*1*0 + optimal.AIC$coefficients[11]*1*age.vals + optimal.AIC$coefficients[12]*0*0 + optimal.AIC$coefficients[13]*0*0 + optimal.AIC$coefficients[14]*0*0 + optimal.AIC$coefficients[15]*0*age.vals)
denom_age_nocit <- 1 + num_age_nocit
probs_age_nocit <- num_age_nocit/denom_age_nocit

lines(age.vals, probs_age_nocit, col = "red")

## Age as predictor, year as categorical variable
num_age_bf2004 <- exp(optimal.AIC$coefficients[1] + optimal.AIC$coefficients[2]*1 + optimal.AIC$coefficients[3]*1 + optimal.AIC$coefficients[4]*1 + optimal.AIC$coefficients[5]*0 + optimal.AIC$coefficients[6]*1 + optimal.AIC$coefficients[7]*19 + optimal.AIC$coefficients[8]*1*1 + optimal.AIC$coefficients[9]*1*age.vals + optimal.AIC$coefficients[10]*1*1 + optimal.AIC$coefficients[11]*1*age.vals + optimal.AIC$coefficients[12]*1*0 + optimal.AIC$coefficients[13]*1*1 + optimal.AIC$coefficients[14]*0*1 + optimal.AIC$coefficients[15]*1*age.vals)
denom_age_bf2004 <- 1 + num_age_bf2004
probs_age_bf2004 <- num_age_bf2004/denom_age_bf2004
  
plot(age.vals, probs_age_bf2004, type = "l", xlab = "Age", ylab = "Predicted Probability of being Held", main = "Pred. Prob. of being Held by time period and age", col = "blue")
legend(0, 0.15, legend = c("Before 2004", "2004 or later"), col = c("blue", "red"), lty = 1:1, cex = 0.8, box.lty = 2, box.lwd = 2, box.col = "green")

num_age_2004l <- exp(optimal.AIC$coefficients[1] + optimal.AIC$coefficients[2]*1 + optimal.AIC$coefficients[3]*1 + optimal.AIC$coefficients[4]*1 + optimal.AIC$coefficients[5]*0 + optimal.AIC$coefficients[6]*0 + optimal.AIC$coefficients[7]*age.vals + optimal.AIC$coefficients[8]*1*0 + optimal.AIC$coefficients[9]*1*age.vals + optimal.AIC$coefficients[10]*1*0 + optimal.AIC$coefficients[11]*1*age.vals + optimal.AIC$coefficients[12]*1*0 + optimal.AIC$coefficients[13]*1*0 + optimal.AIC$coefficients[14]*0*0 + optimal.AIC$coefficients[15]*0*age.vals)
denom_age_2004l <- 1 + num_age_2004l
probs_age_2004l <- num_age_2004l/denom_age_2004l

lines(age.vals, probs_age_2004l, col = "red")
```

```{r}
# PART 6: ASSESS MODEL'S OVERALL FIT (diagnostics)

# 1) Goodness of fit
best.aic<-glm(held ~ race + employed + citizen + databases + 
              year + age + race:year + race:age + employed:year + 
              employed:age + citizen:databases + citizen:year + 
              databases:year + year:age, data=policing2, family=binomial)
best.bic<-glm(held ~ race + employed + citizen + databases+ 
              citizen:databases, data=policing2, family=binomial)
1-pchisq(summary(best.aic)$deviance, summary(best.aic)$df.residual)
1-pchisq(summary(best.bic)$deviance, summary(best.bic)$df.residual)
# Both models are very good fit since p-values are very close to 1

# 2) Classification table
held.probs.aic=best.aic$fitted.values
held.hat.aic=as.numeric(held.probs.aic>0.5)
best.aic.classification<-table(policing2$held, held.hat.aic)
best.aic.classification

held.probs.bic=best.bic$fitted.values
held.hat.bic=as.numeric(held.probs.bic>0.5)
best.bic.classification<-table(policing2$held, held.hat.bic)
best.bic.classification

# 3) ROC curve
plot.roc(policing2$held,held.probs.aic, col="black", 
         main="ROC of two models", xlim=c(1,0), ylim=c(0,1))
plot.roc(policing2$held,held.probs.bic, col="blue", add=T)
legend("topleft", legend=c("AIC Model", "BIC Model"), 
         col=c("black", "blue"), lty=1, cex=.7)
auc(policing2$held,held.probs.aic)
auc(policing2$held,held.probs.bic)
```
